### ISSUE TITLE
Constant 3-5% CPU usage per process

### ISSUE THREAD

**Issue by mnapoli** [papertrail/remote_syslog#73]
Is this kind of CPU usage expected?

![screen](https://f.cloud.github.com/assets/720328/1572676/78d7abd8-5122-11e3-9f80-5b890a8adf68.png)

I find it quite high.

I have several instances running, because I have several applications and I want their log separated by host in PaperTrail. **The configuration is very basic**.

For example, here is the command line of a process:

```
/usr/bin/ruby1.9.1 /usr/local/bin/remote_syslog -D --pid-file /var/run/remote_syslog_demo1.pid -c /etc/logs/demo1.yml
```

and here is the YML config file:

``` yml
files: 
  - /home/web/demo1/data/logs/error.log
  - /home/web/demo1/data/logs/worker.log

hostname: prod.demo1

destination:
  host: logs.papertrailapp.com
  port: XXXX
```

As you can see, the logs here are empty (on other apps, logs are very small for now):

```
$ ll /home/web/demo1/data/logs/
-rwxrwxrwx 1 root root 0 Oct 24 17:37 error.log
-rwxrwxrwx 1 root root 0 Oct 24 17:37 worker.log
```

The server is Ubuntu 13.04, 4 cores (hosted at digital ocean).
